  var i = 1;
    num_Of_Question = 7;
    questions = new Array()
    questions[1] = "What is the 5 digit Greatest No";
    questions[2] = "What is the 3 Digit Smallest No";
    questions[3] = "How many Alphabets in A-Z";
    questions[4] = "What is National fruit of India";
    questions[5] = "What is the National sport Of India";
    questions[6] = "Most Population country in World ";
    questions[7] = "How many sticks in Tiranga (Tricolor) wheel";
        answerA = new Array()
    answerA[1] = "A) 60000";
    answerA[2] = "A) 548";
    answerA[3] = "A) 21";
    answerA[4] = "A) Apple";
    answerA[5] = "A) Basketball";
    answerA[6] = "A) Pakistan";
    answerA[7] = "A) 24";
    answerB = new Array()
    answerB[1] = "B) 66666";
    answerB[2] = "B) 100";
    answerB[3] = "B) 20";
    answerB[4] = "B) Orange";
    answerB[5] = "B) Football";
    answerB[6] = "B) India";
    answerB[7] = "B) 22";
        answerC = new Array()
    answerC[1] = "C) 99999";
    answerC[2] = "C) 111";
    answerC[3] = "C) 26";
    answerC[4] = "C) Mango";
    answerC[5] = "C) Hockey";
    answerC[6] = "C) China";
    answerC[7] = "C) 25";
	answerD = new Array()
	answerD[1] = "D) 77877";
	answerD[2] = "D) 630";
	answerD[3] = "D) 29";
	answerD[4] = "D) Banana";
	answerD[5] = "D) Cricket";
	answerD[6] = "D) Canada";
	answerD[7] = "D) 28";